version: '3'
services:
  front:
    build: 
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - frontend-build:/usr/src/app/build
  back:
    build: 
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./back:/usr/src/app
  nginx:
    image: nginx:1.24
    volumes:
      - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/live/caca.ovh/fullchain.pem:/var/opt/caca.ovh.crt
      - /etc/letsencrypt/live/caca.ovh/privkey.pem:/var/opt/caca.ovh.key
      - frontend-build:/www/data
    ports:
      - "8081:8081"
      - "443:443"
    depends_on:
      - front
      - back
volumes:
 frontend-build:
